### ISSUE TITLE
process ID list syntax error in chroot

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-pac#25] opened 2018-10-13 10:32 UTC
I just ran into the following error:

```
(1/1) Performing snapper pre snapshots for the following configurations...
error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
Failure (dbus fatal exception).
==> error: Exited due to error on line 130
==> root: exit status: 1 command: $snapper_cmd "$(truncate_description $PRE_DESCRIPTION)" bash line: 0 function argv0: main
```

I have to note, that I just copied a backup to a new disk. I executed this inside an arch-chroot environment.

**Comment by NicoHood** [comment] 2018-10-13 11:11
Here is a full error log:
```
[root@bryyo /]# pacman -S nano
warning: nano-3.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) nano-3.1-1

Total Installed Size:  2.29 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                 [#############################################################################] 100%
(1/1) checking package integrity                                                                                               [#############################################################################] 100%
(1/1) loading package files                                                                                                    [#############################################################################] 100%
(1/1) checking for file conflicts                                                                                              [#############################################################################] 100%
(1/1) checking available disk space                                                                                            [#############################################################################] 100%
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
+ set -o errtrace
+ [[ -v SNAP_PAC_SKIP ]]
+ readonly argv0=snap-pac
+ argv0=snap-pac
+ readonly SNAPPAC_CONFIG_FILE=/etc/snap-pac.conf
+ SNAPPAC_CONFIG_FILE=/etc/snap-pac.conf
+ readonly SNAPPER_CONFIG_FILE=/etc/conf.d/snapper
+ SNAPPER_CONFIG_FILE=/etc/conf.d/snapper
+++ ps -p 223 -o ppid=
++ ps -q -o args=
error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
+ readonly pacman_cmd=
+ pacman_cmd=
+ readonly pre_or_post=pre
+ pre_or_post=pre
+ trap 'traperror ${LINENO} $? "$BASH_COMMAND" $BASH_LINENO "${FUNCNAME[@]}"' ERR
+ trap trapkill SIGTERM SIGINT
+ readonly -f read_config out error die trapkill traperror truncate_description
++ awk -F= '/SNAPPER_CONFIGS/ {gsub(/"/, "", $2); print $2}' /etc/conf.d/snapper
+ SNAPPER_CONFIGS='root home'
+ read_config /etc/snap-pac.conf
+ CONFIG_FILE=/etc/snap-pac.conf
+ [[ -f /etc/snap-pac.conf ]]
+ readonly DESC_LIMIT=72
+ DESC_LIMIT=72
+ readonly ABORT_ON_FAIL=no
+ ABORT_ON_FAIL=no
+ readonly LINK_MODULES=no
+ LINK_MODULES=no
+ readonly KERNEL_PACKAGE=linux
+ KERNEL_PACKAGE=linux
+ mapfile -t packages
++ package_updated linux
++ check=linux
++ for x in ${packages[@]}
++ [[ nano == \l\i\n\u\x ]]
++ echo no
+ kernel_updated=no
+ for CONFIG in $SNAPPER_CONFIGS
+ unset SNAPSHOT
+ unset PRE_DESCRIPTION
+ unset POST_DESCRIPTION
+ unset CLEANUP_ALGORITHM
+ read_config /etc/snap-pac/root.conf
+ CONFIG_FILE=/etc/snap-pac/root.conf
+ [[ -f /etc/snap-pac/root.conf ]]
+ [[ root == \r\o\o\t ]]
+ SNAPSHOT=yes
+ PRE_DESCRIPTION=
+ POST_DESCRIPTION=nano
+ CLEANUP_ALGORITHM=number
+ [[ yes == \n\o ]]
+ prefile=/tmp/snap-pac-pre_root
+ snapper_cmd='snapper --config root create --type pre --cleanup-algorithm number --print-number --description'
+ [[ pre == \p\r\e ]]
+++ truncate_description
+++ desc=
+++ [[ 0 -gt 72 ]]
+++ echo
++ snapper --config root create --type pre --cleanup-algorithm number --print-number --description ''
Failure (dbus fatal exception).
+++ traperror 130 1 '$snapper_cmd "$(truncate_description $PRE_DESCRIPTION)"' 0 main
+++ error 'Exited due to error on line 130'
+++ out '==> \033[00;31merror:\033[00m' 'Exited due to error on line 130'
+++ printf '==> \033[00;31merror:\033[00m Exited due to error on line 130\n'
==> error: Exited due to error on line 130
+++ out 'exit status:' 1
+++ printf 'exit status: 1\n'
+++ out command: '$snapper_cmd "$(truncate_description $PRE_DESCRIPTION)"'
+++ printf 'command: $snapper_cmd "$(truncate_description $PRE_DESCRIPTION)"\n'
+++ out 'bash line:' 0
+++ printf 'bash line: 0\n'
+++ out 'function argv0:' main
+++ printf 'function argv0: main\n'
+++ die
+++ [[ no == \n\o ]]
+++ exit 0
+ x='exit status: 1
command: $snapper_cmd "$(truncate_description $PRE_DESCRIPTION)"
bash line: 0
function argv0: main'
++ echo exit status: 1 command: '$snapper_cmd' '"$(truncate_description' '$PRE_DESCRIPTION)"' bash line: 0 function argv0: main
++ tee /tmp/snap-pac-pre_root
+ printf '==> %s: exit status: 1 command: $snapper_cmd "$(truncate_description $PRE_DESCRIPTION)" bash line: 0 function argv0: main\n' root
==> root: exit status: 1 command: $snapper_cmd "$(truncate_description $PRE_DESCRIPTION)" bash line: 0 function argv0: main
+ for CONFIG in $SNAPPER_CONFIGS
+ unset SNAPSHOT
+ unset PRE_DESCRIPTION
+ unset POST_DESCRIPTION
+ unset CLEANUP_ALGORITHM
+ read_config /etc/snap-pac/home.conf
+ CONFIG_FILE=/etc/snap-pac/home.conf
+ [[ -f /etc/snap-pac/home.conf ]]
+ [[ home == \r\o\o\t ]]
+ SNAPSHOT=no
+ PRE_DESCRIPTION=
+ POST_DESCRIPTION=nano
+ CLEANUP_ALGORITHM=number
+ [[ no == \n\o ]]
+ continue
+ exit 0
:: Processing package changes...
(1/1) reinstalling nano                                                                                                        [#############################################################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating the info directory file...
(3/3) Performing snapper post snapshots for the following configurations...
+ set -o errtrace
+ [[ -v SNAP_PAC_SKIP ]]
+ readonly argv0=snap-pac
+ argv0=snap-pac
+ readonly SNAPPAC_CONFIG_FILE=/etc/snap-pac.conf
+ SNAPPAC_CONFIG_FILE=/etc/snap-pac.conf
+ readonly SNAPPER_CONFIG_FILE=/etc/conf.d/snapper
+ SNAPPER_CONFIG_FILE=/etc/conf.d/snapper
+++ ps -p 243 -o ppid=
++ ps -q -o args=
error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
+ readonly pacman_cmd=
+ pacman_cmd=
+ readonly pre_or_post=post
+ pre_or_post=post
+ trap 'traperror ${LINENO} $? "$BASH_COMMAND" $BASH_LINENO "${FUNCNAME[@]}"' ERR
+ trap trapkill SIGTERM SIGINT
+ readonly -f read_config out error die trapkill traperror truncate_description
++ awk -F= '/SNAPPER_CONFIGS/ {gsub(/"/, "", $2); print $2}' /etc/conf.d/snapper
+ SNAPPER_CONFIGS='root home'
+ read_config /etc/snap-pac.conf
+ CONFIG_FILE=/etc/snap-pac.conf
+ [[ -f /etc/snap-pac.conf ]]
+ readonly DESC_LIMIT=72
+ DESC_LIMIT=72
+ readonly ABORT_ON_FAIL=no
+ ABORT_ON_FAIL=no
+ readonly LINK_MODULES=no
+ LINK_MODULES=no
+ readonly KERNEL_PACKAGE=linux
+ KERNEL_PACKAGE=linux
+ mapfile -t packages
++ package_updated linux
++ check=linux
++ for x in ${packages[@]}
++ [[ nano == \l\i\n\u\x ]]
++ echo no
+ kernel_updated=no
+ for CONFIG in $SNAPPER_CONFIGS
+ unset SNAPSHOT
+ unset PRE_DESCRIPTION
+ unset POST_DESCRIPTION
+ unset CLEANUP_ALGORITHM
+ read_config /etc/snap-pac/root.conf
+ CONFIG_FILE=/etc/snap-pac/root.conf
+ [[ -f /etc/snap-pac/root.conf ]]
+ [[ root == \r\o\o\t ]]
+ SNAPSHOT=yes
+ PRE_DESCRIPTION=
+ POST_DESCRIPTION=nano
+ CLEANUP_ALGORITHM=number
+ [[ yes == \n\o ]]
+ prefile=/tmp/snap-pac-pre_root
+ snapper_cmd='snapper --config root create --type post --cleanup-algorithm number --print-number --description'
+ [[ post == \p\r\e ]]
+ [[ -f /tmp/snap-pac-pre_root ]]
+ [[ post == \p\o\s\t ]]
+ [[ no == \y\e\s ]]
+++ truncate_description nano
+++ desc=nano
+++ [[ 4 -gt 72 ]]
+++ echo nano
++ snapper --config root create --type post --cleanup-algorithm number --print-number --description nano --pre-number 'exit status: 1 command: $snapper_cmd "$(truncate_description $PRE_DESCRIPTION)" bash line: 0 function argv0: main'
Failure (dbus fatal exception).
+++ traperror 138 1 '$snapper_cmd "$(truncate_description $POST_DESCRIPTION)" --pre-number "$(< "$prefile")"' 0 main
+++ error 'Exited due to error on line 138'
+++ out '==> \033[00;31merror:\033[00m' 'Exited due to error on line 138'
+++ printf '==> \033[00;31merror:\033[00m Exited due to error on line 138\n'
==> error: Exited due to error on line 138
+++ out 'exit status:' 1
+++ printf 'exit status: 1\n'
+++ out command: '$snapper_cmd "$(truncate_description $POST_DESCRIPTION)" --pre-number "$(< "$prefile")"'
+++ printf 'command: $snapper_cmd "$(truncate_description $POST_DESCRIPTION)" --pre-number "$(< "$prefile")"\n'
+++ out 'bash line:' 0
+++ printf 'bash line: 0\n'
+++ out 'function argv0:' main
+++ printf 'function argv0: main\n'
+++ die
+++ [[ no == \n\o ]]
+++ exit 0
+ x='exit status: 1
command: $snapper_cmd "$(truncate_description $POST_DESCRIPTION)" --pre-number "$(< "$prefile")"
bash line: 0
function argv0: main'
+ printf '==> %s: %s\n' root 'exit status: 1
command: $snapper_cmd "$(truncate_description $POST_DESCRIPTION)" --pre-number "$(< "$prefile")"
bash line: 0
function argv0: main'
==> root: exit status: 1
command: $snapper_cmd "$(truncate_description $POST_DESCRIPTION)" --pre-number "$(< "$prefile")"
bash line: 0
function argv0: main
+ rm -f /tmp/snap-pac-pre_root
+ for CONFIG in $SNAPPER_CONFIGS
+ unset SNAPSHOT
+ unset PRE_DESCRIPTION
+ unset POST_DESCRIPTION
+ unset CLEANUP_ALGORITHM
+ read_config /etc/snap-pac/home.conf
+ CONFIG_FILE=/etc/snap-pac/home.conf
+ [[ -f /etc/snap-pac/home.conf ]]
+ [[ home == \r\o\o\t ]]
+ SNAPSHOT=no
+ PRE_DESCRIPTION=
+ POST_DESCRIPTION=nano
+ CLEANUP_ALGORITHM=number
+ [[ no == \n\o ]]
+ continue
+ exit 0
```

**Comment by NicoHood** [comment] 2018-10-13 11:12
Does the hook even support running without dbus? I guess that is the problem?

**Comment by wesbarnett** [comment] 2019-03-08 17:45
Duplicate of #23

**Closed as completed** 2019-03-08 19:13 UTC
Labels: bug, help wanted
